[server]
host: 0.0.0.0
port: 7125 # plain HTTP port
ssl_port: 7130
klippy_uds_address: /home/sean/printer_data/comms/klippy.sock

[authorization]
force_logins: False # allow trusted clients to connect without login
trusted_clients:
    # 10.0.0.0/8
    127.0.0.0/8
    #169.254.0.0/16
    #172.16.0.0/12
    #192.168.0.0/19
    #192.168.137.0/24
    # FE80::/10
    # ::1/128
cors_domains:
    *.auffinger.dev
    *.lan
#     *.local
#     *://localhost
#     *://localhost:*
#     *://my.mainsail.xyz
#     *://app.fluidd.xyz

[file_manager]
enable_object_processing: True

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main

[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[mqtt]
address: mqtt.auffinger.dev
enable_moonraker_api: False
instance_name: 3dprinter/trident

[sensor ambient]
type: mqtt
name: Ambient
parameter_temperature:
  units=°C
parameter_humidity:
  units=%
state_topic: 3dprinter/trident/htu21d/output
state_response_template:
  {% set notification = payload|fromjson %}
  {set_result("temperature", notification["temperature"]|float)}
  {set_result("humidity", notification["relative_humidity"]|float)}
history_field_temperature:
  parameter=temperature
  desc=Ambient Temperature
  strategy=average
  units=°C
  init_tracker=false
  exclude_paused=false
  report_total=true
  report_maximum=true
  precision=2
history_field_humidity:
  parameter=humidity
  desc=Ambient Humidity
  strategy=average
  units=%
  init_tracker=false
  exclude_paused=false
  report_total=true
  report_maximum=true
  precision=2
[sensor power]
type: mqtt
name: Power
parameter_power:
  units=W
parameter_apparent_power:
  units=VA
parameter_current:
  units=A
parameter_power_factor:
  units=
parameter_total_daily_energy:
  units=kWh
parameter_voltage:
  units=V
parameter_energy:
  units=kWh
state_topic: 3dprinter/trident/powersensor/output
state_response_template:
  {% set notification = payload|fromjson %}
  {set_result("power", notification["power"]|float(default=0)|round(1))}
  {set_result("apparent_power", notification["apparent_power"]|float(default=0)|round(1))}
  {set_result("current", notification["current"]|float(default=0)|round(2))}
  {set_result("power_factor", notification["power_factor"]|float(default=0)|round(2))}
  {set_result("total_daily_energy", notification["total_daily_energy"]|float(default=0)|round(3))}
  {set_result("voltage", notification["voltage"]|float(default=0)|round(1))}
  {set_result("energy", notification["energy"]|float(default=0)|round(3))}
history_field_total_energy:
  parameter=energy
  desc=Power Consumption
  strategy=delta
  units=kWh
  init_tracker=false
  exclude_paused=false
  report_total=true
  report_maximum=true
  precision=3

[spoolman]
server: http://192.168.1.12:8148
sync_rate: 5

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin

[include moonraker-obico-update.cfg]

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail
